name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git remote add space https://t2codes:$HF_TOKEN@huggingface.co/spaces/t2codes/Codemix-Bot
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://t2codes:$HF_TOKEN@huggingface.co/spaces/t2codes/Codemix-Bot main
